/**
 * Golden snapshot tests — pin exact numerical output for all strategies.
 *
 * Each test loads a golden fixture (JSON) generated by golden/generate.ts
 * and compares the current engine output against the stored expectation.
 *
 * Any engine change that shifts a number will cause a visible test failure.
 * To update fixtures after an *intentional* change:
 *     npx -y tsx src/engine/__tests__/golden/generate.ts
 */
import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import type { PlannerConfig, YearRow, ProjectionSummary } from '../types';
import { runProjection } from '../projection';
import { normalizeConfig } from '../strategies';
import { makeExtendedConfig, validateConfig } from '../validation';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const GOLDEN_DIR = path.join(__dirname, 'golden');

const FIXTURES = [
  'fixed_target',
  'fixed_percentage',
  'vanguard_dynamic',
  'guyton_klinger',
  'arva',
  'arva_guardrails',
  'fixed_target_shortfall',
];

interface YearSnapshot {
  age: number;
  target_net: number;
  net_income_achieved: number;
  total_capital: number;
  shortfall: boolean;
}

interface SummarySnapshot {
  sustainable: boolean;
  first_shortfall_age: number | null;
  remaining_capital: number;
  end_age: number;
}

interface GoldenFixture {
  name: string;
  config: PlannerConfig;
  summary: SummarySnapshot;
  years: YearSnapshot[];
  ext_summary: SummarySnapshot;
  ext_years: YearSnapshot[];
  parity_check: {
    plan_end_age: number;
    normal_year_count: number;
    ext_years_within_plan_count: number;
    years_match: boolean;
  };
}

function loadFixture(name: string): GoldenFixture {
  const filePath = path.join(GOLDEN_DIR, `${name}.json`);
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

function extractYear(yr: YearRow): YearSnapshot {
  return {
    age: yr.age,
    target_net: Math.round(yr.target_net * 100) / 100,
    net_income_achieved: Math.round(yr.net_income_achieved * 100) / 100,
    total_capital: Math.round(yr.total_capital * 100) / 100,
    shortfall: yr.shortfall,
  };
}

function extractSummary(s: ProjectionSummary): SummarySnapshot {
  return {
    sustainable: s.sustainable,
    first_shortfall_age: s.first_shortfall_age,
    remaining_capital: Math.round(s.remaining_capital * 100) / 100,
    end_age: s.end_age,
  };
}

for (const fixtureName of FIXTURES) {
  describe(`Golden — ${fixtureName}`, () => {
    const fixture = loadFixture(fixtureName);
    const cfg: PlannerConfig = JSON.parse(JSON.stringify(fixture.config));
    normalizeConfig(cfg);
    const result = runProjection(cfg);
    const extCfg = makeExtendedConfig(cfg);
    const extResult = runProjection(extCfg);
    const planEndAge = cfg.personal.end_age;

    it('config validates', () => {
      const errors = validateConfig(cfg);
      expect(errors).toEqual([]);
    });

    it('summary matches', () => {
      const actual = extractSummary(result.summary);
      expect(actual.sustainable).toBe(fixture.summary.sustainable);
      expect(actual.first_shortfall_age).toBe(fixture.summary.first_shortfall_age);
      expect(actual.remaining_capital).toBeCloseTo(fixture.summary.remaining_capital, 1);
      expect(actual.end_age).toBe(fixture.summary.end_age);
    });

    it('year count matches', () => {
      expect(result.years.length).toBe(fixture.years.length);
    });

    it('year-by-year matches', () => {
      for (let i = 0; i < result.years.length; i++) {
        const actual = extractYear(result.years[i]!);
        const expected = fixture.years[i]!;
        expect(actual.age).toBe(expected.age);
        expect(actual.target_net).toBeCloseTo(expected.target_net, 1);
        expect(actual.net_income_achieved).toBeCloseTo(expected.net_income_achieved, 1);
        expect(actual.total_capital).toBeCloseTo(expected.total_capital, 1);
        expect(actual.shortfall).toBe(expected.shortfall);
      }
    });

    it('extended projection parity', () => {
      const normalYears = result.years.map(extractYear);
      const extYearsWithinPlan = extResult.years
        .filter(y => y.age <= planEndAge)
        .map(extractYear);
      expect(normalYears.length).toBe(extYearsWithinPlan.length);
      for (let i = 0; i < normalYears.length; i++) {
        const ny = normalYears[i]!;
        const ey = extYearsWithinPlan[i]!;
        expect(ny.age).toBe(ey.age);
        expect(ny.target_net).toBeCloseTo(ey.target_net, 1);
        expect(ny.net_income_achieved).toBeCloseTo(ey.net_income_achieved, 1);
        expect(ny.total_capital).toBeCloseTo(ey.total_capital, 1);
        expect(ny.shortfall).toBe(ey.shortfall);
      }
    });
  });
}

// Extra assertion for the shortfall fixture
describe('Golden — fixed_target_shortfall extras', () => {
  const fixture = loadFixture('fixed_target_shortfall');
  const cfg: PlannerConfig = JSON.parse(JSON.stringify(fixture.config));
  normalizeConfig(cfg);
  const result = runProjection(cfg);

  it('is a shortfall scenario', () => {
    expect(result.summary.sustainable).toBe(false);
    expect(result.summary.first_shortfall_age).not.toBeNull();
  });
});
